version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install

  build:
    commands:
      - npx prisma generate
      - npx prisma migrate deploy
      - npm run build

artifacts:
  files:
    - '**/*'
